[env]
MAS_NO_AUTO_INDEX = "1"

[settings]
github_attestations = true
gpg_verify = true
install_before = "7d"
lockfile = true
slsa = true

[tools]
jq = "latest"
pkl = "latest"
rumdl = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"

[tools.hk]
postinstall = "hk install --mise"
version = "1.54"

[vars]
git_user_name = "Balint Antal"
git_signingkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDJi9Fk7go7rlgKX1+acIo5Dnl0mjV1hFbPHW/LxvNW5"
