[bootstrap.packages]
"brew:bat" = "latest"
"brew:cfn-lint" = "latest"
"brew:coreutils" = "latest"
"brew:curl" = "latest"
"brew:diff-so-fancy" = "latest"
"brew:docker" = "latest"
"brew:fd" = "latest"
"brew:fzf" = "latest"
"brew:gh" = "latest"
"brew:git-lfs" = "latest"
"brew:git" = "latest"
"brew:jq" = "latest"
"brew:mas" = "latest"
"brew:neovim" = "latest"
"brew:smartmontools" = "latest"
"brew:speedtest-cli" = "latest"
"brew:stow" = "latest"
"brew:swagger-codegen" = "latest"
"brew:tig" = "latest"
"brew:tmux" = "latest"
"brew:tree" = "latest"
"brew:watch" = "latest"
"brew:watchman" = "latest"
"brew:yq" = "latest"
