# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Something like oh-my-zsh's "pygmalion" theme, as I'm used to that.
add_newline = false
format = """
$username\
$hostname\
$directory\
[|](red)\
$git_branch${custom.git_dirty}\
[⇒](cyan)  """

[username]
format      = "[$user](purple)"
show_always = true

[hostname]
format   = "[@](cyan)[$hostname](yellow)"
ssh_only = false

[directory]
truncate_to_repo  = false
truncation_symbol = "~/"
format            = "[:](red)[$path](cyan)"

[git_branch]
format = "[$branch](green)"

[custom.git_dirty]
when   = "[[ $(git status -s) != '' ]]"
format = "[⚡ ](yellow)"

[package]
disabled = true
