[env]
_.source = '{{ cwd }}/.envrc'

[tools]
awscli = "latest"
bun = "latest"
cmake = "latest"
fly = "latest"
golang = "latest"
hk = "latest"
java = "latest"
kotlin = "latest"
make = "latest"
node = "lts"
pkl = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
